const ENTER_ASCII_CODE = 13;
const BAD_REQUEST_CODE = 400;
const UPLOAD_IMAGE_TIMEOUT = 2000;
const UPLOAD_DONE_TIMEOUT = 4000;

const GOOGLE_MAPS_URL = 'https://maps.google.com/maps';

export {
  ENTER_ASCII_CODE,
  BAD_REQUEST_CODE,
  UPLOAD_DONE_TIMEOUT,
  UPLOAD_IMAGE_TIMEOUT,
  GOOGLE_MAPS_URL
};
