const GET_GALLERY_SUCCESS = 'GET_GALLERY_SUCCESS';
const GET_GALLERY_FAILURE = 'GET_GALLERY_FAILURE';
const GET_GALLERY_STARTED = 'GET_GALLERY_STARTED';
const FILTER_ADD = 'FILTER_ADD';
const FILTER_REMOVE = 'FILTER_REMOVE';
const FILTER_RESET = 'FILTER_RESET';

export {
  GET_GALLERY_SUCCESS,
  GET_GALLERY_FAILURE,
  GET_GALLERY_STARTED,
  FILTER_ADD,
  FILTER_REMOVE,
  FILTER_RESET
};
