const GET_GALLERY_SUCCESS = 'GET_GALLERY_SUCCESS';
const GET_GALLERY_FAILURE = 'GET_GALLERY_FAILURE';
const GET_GALLERY_STARTED = 'GET_GALLERY_STARTED';

export {
  GET_GALLERY_SUCCESS,
  GET_GALLERY_FAILURE,
  GET_GALLERY_STARTED
};
