const POST_UPLOAD_SUCCESS = 'POST_UPLOAD_SUCCESS';
const POST_UPLOAD_FAILURE = 'POST_UPLOAD_FAILURE';
const POST_UPLOAD_STARTED = 'POST_UPLOAD_STARTED';
const POST_UPLOAD_CLEAR_DONE = 'POST_UPLOAD_CLEAR_DONE';

export {
  POST_UPLOAD_SUCCESS,
  POST_UPLOAD_FAILURE,
  POST_UPLOAD_STARTED,
  POST_UPLOAD_CLEAR_DONE
};
